#!/bin/sh

bindir="`dirname $0`"

ZM="$bindir/zm"

usage_error () {
    message="$1"
    echo "$message"
    exit 2
}

[ $# -ge 1 ] || usage_error "No domain specified"
domain="$1" ; shift

# Start test
testid="`"${ZM}" start_domain_test "$domain" | jq -r .result`"

# Wait for test to finish
while true
do
    progress="`"${ZM}" test_progress "$testid" | jq -r .result`"
    echo -n "\r$progress% done" >&2
    if [ "$progress" -eq 100 ] ; then
        echo
        break
    fi
    sleep 1
done

# Get test results
"${ZM}" get_test_results "$testid"
echo "testid:" $testid >&2
