#!/bin/sh

bindir="`dirname $0`"

ZMB="$bindir/zmb"

usage_error () {
    message="$1"
    echo "$message" >&2
    exit 2
}

zmb () {
    json="`"${ZMB}" "$@"`"
    if echo "$json" | jq -e .error > /dev/null ; then
        echo "error: method $1: $json" >& 2
        exit 1
    else
        echo "$json"
    fi
}

[ $# -ge 1 ] || usage_error "No domain specified"
domain="$1" ; shift

# Start test
testid="`zmb start_domain_test --domain "$domain" | jq -r .result`" || exit 1

# Wait for test to finish
while true
do
    progress="`zmb test_progress --testid "$testid" | jq -r .result`" || exit 1
    echo -n "\r$progress% done" >&2
    if [ "$progress" -eq 100 ] ; then
        echo >&2
        break
    fi
    sleep 1
done

# Get test results
zmb get_test_results --testid "$testid" --lang en
echo "testid:" $testid >&2
